### ISSUE TITLE
FIX Azure GetAudioForProfileTrigger mscorlib error

### ISSUE THREAD

**Issue by RazvanBerbece** [RazvanBerbece/cete-api#76]
## Description
Error occuring on GetAudioForProfileTrigger run in Azure (stg).

## Fix attempts
1.  Updated the dependencies in ```package.json```, run npm update & save
2. Updated infrastructure ([Source PR](https://github.com/RazvanBerbece/cete-infrastructure/pull/47))
3. Removed connections using connection strings and opted for URIs & keys

## Traces
```
Exception while executing function: Functions.GetAudioForProfileTrigger. mscorlib: One or more errors occurred. C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13694
async function delay(timeInMs, aborter, abortError) {
      ^^^^^^^^

SyntaxError: Unexpected token function
    at createScript (vm.js:56:10)
    at Object.runInThisContext (vm.js:97:10)
    at Module._compile (module.js:542:28)
    at Object.Module._extensions..js (module.js:579:10)
    at Module.load (module.js:487:32)
    at tryModuleLoad (module.js:446:12)
    at Function.Module._load (module.js:438:3)
    at Module.require (module.js:497:17)
    at require (internal/module.js:20:19)
    at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24).
```

## Resolution
'Fix attempts' no.2 and no.3 were what the on-Azure deployment needed in order to function again.

**Comment by RazvanBerbece** [comment]
## Azure Filesystem Logs (Log Stream)

```
2022-03-16T20:28:22  Welcome, you are now connected to log-streaming service. The default timeout is 2 hours. Change the timeout with the App Setting SCM_LOGSTREAM_TIMEOUT (in seconds).
2022-03-16T20:28:27.836 [Info] Executing HTTP request: {"requestId": "7a0b7e0a-0cbb-427a-9690-47e66a129c94","method": "GET","uri": "/api/v1/get/profile/cetes"}
2022-03-16T20:28:28.039 [Info,GetAudioForProfileTrigger] Function started (Id=45c997a3-9f74-4ea0-ad93-a0dcc6fca7c4)
2022-03-16T20:28:28.289 [Info,GetAudioForProfileTrigger] Executing 'Functions.GetAudioForProfileTrigger' (Reason='This function was programmatically called via the host APIs.', Id=45c997a3-9f74-4ea0-ad93-a0dcc6fca7c4)
2022-03-16T20:28:31.571 [Error] A ScriptHost error has occurred
2022-03-16T20:28:31.571 [Error] C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13846async function delay(timeInMs, aborter, abortError) {^^^^^^^^SyntaxError: Unexpected token functionat createScript (vm.js:56:10)at Object.runInThisContext (vm.js:97:10)at Module._compile (module.js:542:28)at Object.Module._extensions..js (module.js:579:10)at Module.load (module.js:487:32)at tryModuleLoad (module.js:446:12)at Function.Module._load (module.js:438:3)at Module.require (module.js:497:17)at require (internal/module.js:20:19)at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24)
2022-03-16T20:28:31.581 [Error,GetAudioForProfileTrigger] Exception while executing function: Functions.GetAudioForProfileTrigger. mscorlib: One or more errors occurred. C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13846async function delay(timeInMs, aborter, abortError) {^^^^^^^^SyntaxError: Unexpected token functionat createScript (vm.js:56:10)at Object.runInThisContext (vm.js:97:10)at Module._compile (module.js:542:28)at Object.Module._extensions..js (module.js:579:10)at Module.load (module.js:487:32)at tryModuleLoad (module.js:446:12)at Function.Module._load (module.js:438:3)at Module.require (module.js:497:17)at require (internal/module.js:20:19)at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24).
2022-03-16T20:28:31.596 [Error,GetAudioForProfileTrigger] Exception while executing function: Functions.GetAudioForProfileTrigger
2022-03-16T20:28:31.596 [Error,GetAudioForProfileTrigger] C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13846async function delay(timeInMs, aborter, abortError) {^^^^^^^^SyntaxError: Unexpected token functionat createScript (vm.js:56:10)at Object.runInThisContext (vm.js:97:10)at Module._compile (module.js:542:28)at Object.Module._extensions..js (module.js:579:10)at Module.load (module.js:487:32)at tryModuleLoad (module.js:446:12)at Function.Module._load (module.js:438:3)at Module.require (module.js:497:17)at require (internal/module.js:20:19)at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24)
2022-03-16T20:28:31.631 [Error,GetAudioForProfileTrigger] Function completed (Failure, Id=45c997a3-9f74-4ea0-ad93-a0dcc6fca7c4, Duration=3590ms)
2022-03-16T20:28:31.691 [Error,GetAudioForProfileTrigger] Executed 'Functions.GetAudioForProfileTrigger' (Failed, Id=45c997a3-9f74-4ea0-ad93-a0dcc6fca7c4)
2022-03-16T20:28:31.691 [Error,GetAudioForProfileTrigger] C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13846async function delay(timeInMs, aborter, abortError) {^^^^^^^^SyntaxError: Unexpected token functionat createScript (vm.js:56:10)at Object.runInThisContext (vm.js:97:10)at Module._compile (module.js:542:28)at Object.Module._extensions..js (module.js:579:10)at Module.load (module.js:487:32)at tryModuleLoad (module.js:446:12)at Function.Module._load (module.js:438:3)at Module.require (module.js:497:17)at require (internal/module.js:20:19)at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24)
2022-03-16T20:28:31.691 [Error,GetAudioForProfileTrigger] Function had errors. See Azure WebJobs SDK dashboard for details. Instance ID is '45c997a3-9f74-4ea0-ad93-a0dcc6fca7c4'
2022-03-16T20:28:31.691 [Error,GetAudioForProfileTrigger] C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13846async function delay(timeInMs, aborter, abortError) {^^^^^^^^SyntaxError: Unexpected token functionat createScript (vm.js:56:10)at Object.runInThisContext (vm.js:97:10)at Module._compile (module.js:542:28)at Object.Module._extensions..js (module.js:579:10)at Module.load (module.js:487:32)at tryModuleLoad (module.js:446:12)at Function.Module._load (module.js:438:3)at Module.require (module.js:497:17)at require (internal/module.js:20:19)at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24)
2022-03-16T20:28:31.799 [Error] {"id":"600e7b77-7694-4507-93c4-f2ea0d3d5be3","requestId":"7a0b7e0a-0cbb-427a-9690-47e66a129c94","statusCode":500,"errorCode":0,"message":"An error has occurred. For more information, please check the logs for error ID 600e7b77-7694-4507-93c4-f2ea0d3d5be3"}
2022-03-16T20:28:31.799 [Error] C:\home\site\wwwroot\node_modules\@azure\storage-blob\dist\index.js:13846async function delay(timeInMs, aborter, abortError) {^^^^^^^^SyntaxError: Unexpected token functionat createScript (vm.js:56:10)at Object.runInThisContext (vm.js:97:10)at Module._compile (module.js:542:28)at Object.Module._extensions..js (module.js:579:10)at Module.load (module.js:487:32)at tryModuleLoad (module.js:446:12)at Function.Module._load (module.js:438:3)at Module.require (module.js:497:17)at require (internal/module.js:20:19)at Object.<anonymous> (C:\home\site\wwwroot\dist\models\AzureBlobStorageClient\BlobClient.js:29:24)
```
